spring:
  datasource:
    username: sa
    password: 1234
    url: jdbc:mysql://localhost:3306/InternShipManagement?trustServerCertificate=true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

mail:
  host: smtp.gmail.com
  username: ${mail-username}
  password: ${mail-password}
  from: ${mail-username}
  port: 587
  properties:
    mail:
      transport:
        protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000

firebase:
  path: ${GOOGLE_APPLICATION_CREDENTIALS}
  api_key: ${WEB_API_KEY}